### ISSUE TITLE
update 2

### ISSUE THREAD

**Issue by KashunEnspirer** [Enspirer/PMP1#5]
![image](https://user-images.githubusercontent.com/85350148/130765781-42c544d9-3f3f-4706-9b91-d89eda6a61de.png)

Remove this section

**Comment by imzajjithvedha** [comment]
Fixed

**Comment by sanjayaharshana** [comment]
its not removed change title, Its Fixed . Thanks

**Comment by sanjayaharshana** [comment]
Fixed
